### ISSUE TITLE
Error: The `asyncapi` field is missing.

### ISSUE THREAD

**Issue by DanielBo** [asyncapi/jasyncapi-idea-plugin#23]
#### Describe the bug

This bug has been around before Version 1.7.0 and was supposedly fixed last Octorber. However it just appeared on me.

![image](https://user-images.githubusercontent.com/3023733/229100288-60a4c9d1-1e9c-487a-9e8c-351efb284e79.png)

#### How to Reproduce
- installed asyncapiCLI
- created a sample file using
  `asyncapi new --example=tutorial.yml --no-tty`
- installed ansycApiPlugin for IntelliJ
- restarted IntelliJ
- opened the file, opened previewer

to elaborate on my Setup:
- Running on M1 with Ventura 13.0.1
- IntelliJ 2022.3.2 Ultimate Edition
- AsyncApi 2.0.0+jre17

#### Expected behavior
I was expecting the plugin to show me a preview of the freshly generated sample.

**Comment by Pakisan** [comment]
@DanielBo hi!

Two requests to help me:
- Can you attach generated specification?
- Can you open the preview in the browser and check the console for errors or try to open the file via generated link?

I will check it in 2.0.0+jre17. Previously problem was in the path separator, I used a fixed separator instead of platform independent, so that was a reason why the preview couldn't open file from temporal folder.
